USE ROLE DLAI_LAB_RL;
USE WAREHOUSE DLAI_LAB_WH;

CREATE SCHEMA IF NOT EXISTS DLAI_AGENT_ENGINEERING.L1_LAB;

CREATE OR REPLACE VIEW DLAI_AGENT_ENGINEERING.L1_LAB.FCT_SALES AS
  SELECT * FROM DLAI_AGENT_ENGINEERING.L1_FX_SOURCE.FCT_SALES;
CREATE OR REPLACE VIEW DLAI_AGENT_ENGINEERING.L1_LAB.ORDER_PAYMENTS AS
  SELECT * FROM DLAI_AGENT_ENGINEERING.L1_FX_SOURCE.ORDER_PAYMENTS;
CREATE OR REPLACE VIEW DLAI_AGENT_ENGINEERING.L1_LAB.DIM_EXCHANGE_RATES AS
  SELECT * FROM DLAI_AGENT_ENGINEERING.L1_FX_SOURCE.DIM_EXCHANGE_RATES;

DROP TABLE IF EXISTS DLAI_AGENT_ENGINEERING.L1_LAB.FACT_REVENUE;
DROP VIEW IF EXISTS DLAI_AGENT_ENGINEERING.L1_LAB.FACT_REVENUE;

SELECT 'FCT_SALES' AS RELATION, COUNT(*) AS ROW_COUNT FROM DLAI_AGENT_ENGINEERING.L1_LAB.FCT_SALES
UNION ALL
SELECT 'ORDER_PAYMENTS', COUNT(*) FROM DLAI_AGENT_ENGINEERING.L1_LAB.ORDER_PAYMENTS
UNION ALL
SELECT 'DIM_EXCHANGE_RATES', COUNT(*) FROM DLAI_AGENT_ENGINEERING.L1_LAB.DIM_EXCHANGE_RATES;