export const catalog = [
  ["catalog_search_objects", "catalog", "Search databases, schemas, tables, and views by name."],
  ["catalog_list_databases", "catalog", "List databases visible to the active Snowflake role."],
  ["catalog_list_schemas", "catalog", "List schemas in a Snowflake database."],
  ["catalog_list_relations", "catalog", "List tables in a Snowflake schema."],
  ["schema_describe_table", "schema", "Describe table columns, types, nullability, and comments."],
  ["schema_list_columns", "schema", "Return compact column metadata for a table or view."],
  ["schema_primary_keys", "schema", "Show declared primary-key metadata for a table."],
  ["schema_foreign_keys", "schema", "Show declared foreign-key metadata for a table."],
  ["sql_query", "sql", "Run one read-only SQL statement and return bounded structured rows."],
  ["sql_profile_table", "sql", "Profile table row counts, nulls, distinct values, and ranges."],
  ["sql_sample_rows", "sql", "Return a bounded row sample from a table."],
  ["sql_explain", "sql", "Compile and explain a read-only Snowflake query."],
  ["sql_query_history", "sql", "Inspect recent read-only query history for the active user."],
  ["dbt_compile", "dbt", "Compile the focused dbt project without executing models."],
  ["dbt_build", "dbt", "Build the focused dbt project and run visible tests."],
  ["dbt_test", "dbt", "Run visible dbt tests for the focused project."],
  ["dbt_list", "dbt", "List dbt resources in the focused project."],
  ["warehouse_status", "operations", "Show status and size of visible Snowflake warehouses."],
  ["warehouse_load_history", "operations", "Inspect recent warehouse load and queue metrics."],
  ["task_history", "operations", "Inspect recent Snowflake task executions."],
  ["dynamic_table_refresh_history", "operations", "Inspect dynamic-table refresh status."],
  ["stage_list_files", "ingestion", "List files on an authorized Snowflake stage."],
  ["copy_history", "ingestion", "Inspect recent COPY ingestion history."],
  ["pipe_status", "ingestion", "Inspect Snowpipe status without modifying the pipe."],
  ["access_show_grants", "governance", "Show grants on an object."],
  ["access_policy_references", "governance", "Find policies attached to an object."],
  ["lineage_upstream", "governance", "Find upstream dependencies for a Snowflake object."],
  ["lineage_downstream", "governance", "Find downstream dependencies for a Snowflake object."],
  ["cost_warehouse_usage", "cost", "Summarize warehouse credit usage."],
  ["cost_query_attribution", "cost", "Inspect query-level cost attribution."],
].map(([name, category, description]) => ({ name, category, description }));

export const implementedTools = new Set([
  "catalog_list_databases",
  "catalog_list_schemas",
  "catalog_list_relations",
  "schema_describe_table",
  "schema_list_columns",
  "sql_query",
  "sql_profile_table",
  "sql_sample_rows",
  "sql_explain",
  "dbt_compile",
  "dbt_build",
  "dbt_test",
  "dbt_list",
  "warehouse_status",
]);